import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mainSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Or create a sidebar manually
  mainSidebar: [
    // 'index',
    {
      type: 'doc',
      id: 'index',
      label: 'Overview',
    },

    {
      type: 'doc',
      id: 'tokens',
      label: 'Tokens',
    },
    {
      type: 'category',
      label: 'Styles',
      // link: {
      //   type: 'doc',
      //   id: 'tokens',
      // },
      items: [
        'styles/layout',
        'styles/flexbox-and-grid',
        'styles/spacing',
        'styles/sizing',
        'styles/typography',
        'styles/backgrounds',
        'styles/borders',
        'styles/effects',
        'styles/filters',
        'styles/tables',
        'styles/animation',
        'styles/transforms',
        'styles/interactivity',
      ],
    },

    {
      type: 'category',
      label: 'Colors',
      items: ['colors/radix', 'colors/tailwind', 'colors/web', 'colors/libretone'],
    },
    // {
    //   type: 'link',
    //   href: '/sandbox',
    //   label: 'Sandbox',
    // },
    'elements/index',

    {
      type: 'category',
      label: 'React Components',
      link: {
        type: 'doc',
        id: 'components/index',
        // //   type: 'generated-index',
        // //   title: 'Components',
      },
      items: [
        // { type: 'autogenerated', dirName: 'components' }
        'components/accordion',
        'components/alert-dialog',
        'components/aspect-ratio',
        'components/avatar',
        'components/badge',
        'components/button',
        'components/callout',
        'components/card',
        'components/checkbox-cards',
        'components/checkbox-group',
        'components/checkbox',
        'components/color-picker',
        'components/context-menu',
        'components/data-list',
        'components/dialog',
        'components/dropdown-menu',
        'components/hover-card',
        'components/icon-button',
        // 'components/index',
        'components/inset',
        'components/popover',
        'components/progress',
        'components/radio-cards',
        'components/radio-group',
        'components/radio',
        'components/scroll-area',
        'components/segmented-control',
        'components/select',
        'components/separator',
        'components/skeleton',
        'components/slider',
        'components/spinner',
        'components/switch',
        'components/table',
        'components/tabs',
        'components/text-area',
        'components/text-field',
        'components/tooltip',
      ],
      // collapsed: false,
    },
    {
      type: 'category',
      label: 'Layout patterns',
      link: {
        type: 'doc',
        id: 'layouts/index',
      },
      items: []
    },

    // {
    //   type: 'category',
    //   label: 'Form',
    //   // link: {
    //   //   type: 'doc',
    //   //   id: 'form/index'
    //   //   // type: 'generated-index',
    //   //   // title: 'Form',
    //   // },
    //   items: [{ type: 'autogenerated', dirName: 'form' }],
    //   // collapsed: false,
    // },
    // // { type: 'html', value: `<hr>` },
    // // 'content',
    // // 'layout',
    // // 'utilities',

    // // { type: 'autogenerated', dirName: 'examples' },
    // [
    //   {
    //     type: 'html',
    //     value: `<hr><b style="margin-left:.75rem;">Example Pages</b>`,
    //   },
    //   // {
    //   //   type: 'link',
    //   //   href: '/sandbox',
    //   //   label: 'Sandbox',
    //   // },

    //   { type: 'link', label: 'Album', href: '/examples/album' },
    //   { type: 'link', label: 'Badges', href: '/examples/badges' },
    //   { type: 'link', label: 'Blog', href: '/examples/blog' },
    //   { type: 'link', label: 'Breadcrumbs', href: '/examples/breadcrumbs' },
    //   { type: 'link', label: 'Buttons', href: '/examples/buttons' },
    //   { type: 'link', label: 'Carousel', href: '/examples/carousel' },
    //   { type: 'link', label: 'Checkout', href: '/examples/checkout' },
    //   { type: 'link', label: 'Cover', href: '/examples/cover' },
    //   { type: 'link', label: 'Dashboard', href: '/examples/dashboard' },
    //   { type: 'link', label: 'Dropdowns', href: '/examples/dropdowns' },
    //   { type: 'link', label: 'Features', href: '/examples/features' },
    //   { type: 'link', label: 'Footers', href: '/examples/footers' },
    //   { type: 'link', label: 'Grid', href: '/examples/grid' },
    //   { type: 'link', label: 'Headers', href: '/examples/headers' },
    //   { type: 'link', label: 'Heroes', href: '/examples/heroes' },
    //   { type: 'link', label: 'Jumbotron', href: '/examples/jumbotron' },
    //   { type: 'link', label: 'Jumbotrons', href: '/examples/jumbotrons' },
    //   { type: 'link', label: 'List groups', href: '/examples/list-groups' },
    //   // { type: 'link', label: 'masonry', href: '/examples/masonry' },
    //   { type: 'link', label: 'Modals', href: '/examples/modals' },
    //   { type: 'link', label: 'Navbar bottom', href: '/examples/navbar-bottom' },
    //   { type: 'link', label: 'Navbar fixed', href: '/examples/navbar-fixed' },
    //   { type: 'link', label: 'Navbars', href: '/examples/navbars' },
    //   {
    //     type: 'link',
    //     label: 'Navbars offcanvas',
    //     href: '/examples/navbars-offcanvas',
    //   },
    //   {
    //     type: 'link',
    //     label: 'Navbar -static',
    //     href: '/examples/navbar-static',
    //   },
    //   {
    //     type: 'link',
    //     label: 'Offcanvas navbar',
    //     href: '/examples/offcanvas-navbar',
    //   },
    //   { type: 'link', label: 'Pricing', href: '/examples/pricing' },
    //   { type: 'link', label: 'Product', href: '/examples/product' },
    //   { type: 'link', label: 'Sidebars', href: '/examples/sidebars' },
    //   { type: 'link', label: 'Sign-in', href: '/examples/sign-in' },
    //   {
    //     type: 'link',
    //     label: 'Starter template',
    //     href: '/examples/starter-template',
    //   },
    //   { type: 'link', label: 'Sticky footer', href: '/examples/sticky-footer' },
    //   {
    //     type: 'link',
    //     label: 'Sticky footer navbar',
    //     href: '/examples/sticky-footer-navbar',
    //   },
    //   {
    //     type: 'link',
    //     label: 'Theme switcher',
    //     href: '/examples/theme-switcher',
    //   },
    // ],

    // // {
    // //   type: 'category',
    // //   label: 'Examples',
    // //   // link: {
    // //   //   type: 'generated-index',
    // //   //   title: 'Examples',
    // //   // },
    // //   items: [
    // //     // { type: 'autogenerated', dirName: '../lib/examples' }
    // //   ]
    // // },
  ],
}

export default sidebars
