import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mainSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Or create a sidebar manually
  mainSidebar: [
    'index',
    // 'all/index',
    'atoms',
    'colors',
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'generated-index',
        title: 'Components',
      },
      items: [{ type: 'autogenerated', dirName: 'components' }]
    },
    {
      type: 'category',
      label: 'Form',
      // link: {
      //   type: 'doc',
      //   id: 'form/index'
      //   // type: 'generated-index',
      //   // title: 'Form',
      // },
      items: [{ type: 'autogenerated', dirName: 'form' }]
    },
    { type: 'html', value: `<hr>`},
    'content',
    'layout',
    'utilities',
    { type: 'html', value: `<hr><b style="margin-left:.75rem;">Examples</b>`},
    { type: 'autogenerated', dirName: 'examples' },
    // {
    //   type: 'category',
    //   label: 'Examples',
    //   link: {
    //     type: 'generated-index',
    //     title: 'Examples',
    //   },
    //   items: [{ type: 'autogenerated', dirName: 'examples' }]
    // },
  ],
}

export default sidebars
